# main menu navigation
menu:
  Home: /
  Blog: /blog
  About: /about
#  Contact: /contact
#  Archives: /archives

# Miscellaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/core.css

# scripts loaded in the end of the body
scripts:
- /js/core.js
