backend:
  name: git-gateway
  branch: development
publish_mode: editorial_workflow
media_folder: "images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
